Cancel delete admin requests
beer-garden/beer-garden pull request #1659
Opened 2024-10-02 17:58 UTC by TheBurchLog

Fixes: #1658 

![image](https://github.com/user-attachments/assets/b3d9765c-81dd-41a4-86fb-3b9cff04087a)

2024-10-04 10:32 UTC, 1maple1 requested changes
Double check cancel vs delete.

2024-10-04 10:32 UTC, 1maple1 commented on src/app/beer_garden/requests.py
> +    logger.info(f"Cancled {len(requests)} requests")
spelling: Canceled

2024-10-04 10:32 UTC, 1maple1 commented on src/ui/src/templates/admin_request_delete.html
> +          Cancel CREATED
Delete CREATED

2024-10-07 13:17 UTC, TheBurchLog commented
UI Updates:
![image](https://github.com/user-attachments/assets/0346afce-a50a-435f-960a-ae4c9f7e64d1)

2024-10-09 18:14 UTC, 1maple1 approved these changes
Great, overall looks a bit more streamlined.

2024-10-09 18:18 UTC, merged