Added handler for unresponsive child gardens
beer-garden/beer-garden pull request #520
Opened 2020-07-22 14:13 UTC by TheBurchLog

When a failure occurs when publishing to a down stream Garden, we can now throw an event that can be handled by correctly for each Payload Type. In this commit we are handling the Garden Status change and Request Creates.

Fixes #513

2020-07-22 16:30 UTC, hazmat345 commented
@TheBurchLog OK, I figured out why none of the Tornado logs were showing up, at least. See 92bfad3a.

I'd recommend rebasing this onto v3 for debugging purposes.

2020-07-22 17:44 UTC, TheBurchLog commented
@hazmat345 
I see what is happening. I only handled what happens when the connection fails. Not what happens when the Admin didnt' configure the connection.

2020-07-22 17:54 UTC, TheBurchLog commented
@hazmat345 

Try it out now. I did the following use cases

1. New BG connected and connection info not set.
1. New BG connected and connection info set properly
1. New BG connected and connection info set properly, then changed to wrong connection info

2020-08-05 11:49 UTC, TheBurchLog commented
@hazmat345 
Can you run through the test criteria again and let me know if you are still seeing the issue you documented?

2020-08-25 12:28 UTC, TheBurchLog commented
@hazmat345 Updated the Status and Events for the Gardens to reflect the different scenarios we could be in.

2020-10-02 21:28 UTC, hazmat345 commented
@TheBurchLog this needs to be rebased onto v3 to test... I tried to do this and made issue/513 branches in both beer-garden and brewtils. Check them out and see if they look reasonable, but feel free to ignore them :smile: 

I did test in v3 to see if this is still a problem and it is.

2020-10-05 22:54 UTC, hazmat345 requested changes
Ok, this definitely fixes the problem. Instead of a request that hangs forever in CREATED the request errors. But there are a couple issues to be addressed.

2020-10-05 22:54 UTC, hazmat345 commented on src/app/beer_garden/requests.py
> +
I really don't like doing this in the garden module. Can we just call `complete_request` directly in the error handling of the `forward` function?

2020-10-05 22:54 UTC, hazmat345 commented on src/app/beer_garden/requests.py
> +                error_class=event.error_message,
The error class is supposed to be a literal class name. If you want to make the error message part of the request you should put it in the output, but make sure you look at how brewtils does that. There should be a format function that you need to call to account for if the output should be JSON or not.

2020-10-05 22:54 UTC, hazmat345 commented on src/app/beer_garden/router.py
> +        raise ex
If you're re-raising an exception like this the statement needs to be just `raise`, not `raise ex`. The way it is now is going to be reported in the stacktraces as the exception handling for the first exception encountering a problem and raising a *new* exception (that happens to be identical to the first one). That's how we get these long chained exceptions with "error encountered while processing exception..." in the logs.

2020-10-06 16:45 UTC, hazmat345 approved these changes
This looks good, only thing is that the output should be run through the same code path as plugin-generated errors in order to match what the plugins do (this prevents JSON parse errors for system clients that are expecting JSON).

However, I'm not sure that's still what we should be doing, so I'm going to open a new issue to address.

2020-10-06 17:19 UTC, merged