Disables Pour it Again issue #624
beer-garden/beer-garden pull request #762
Opened 2020-11-24 17:00 UTC by west270

Disables `Pour it Again` button if system or command is not found.

Fixes #624

2020-11-25 12:05 UTC, TheBurchLog reviewed
Looks good, minus the few changes suggested. Once you get those fixed go ahead and merge this in.

2020-11-25 12:05 UTC, TheBurchLog commented on src/ui/src/js/controllers/request_view.js
> +  'NamespaceService',
Unused import `NamespaceService`

2020-11-25 12:05 UTC, TheBurchLog commented on src/ui/src/js/controllers/request_view.js
> +    NamespaceService) {
Unused import `NamespaceService`

2020-11-30 15:42 UTC, TheBurchLog approved these changes

2020-11-30 17:54 UTC, hazmat345 requested changes
Some missing semicolons. Other than that looks good and works for me.

2020-11-30 17:54 UTC, hazmat345 commented on src/ui/src/js/controllers/request_view.js
> +    let namespace = $scope.request.namespace || $scope.config.gardenName
;

2020-11-30 17:54 UTC, hazmat345 commented on src/ui/src/js/controllers/request_view.js
> +                $scope.msgPourItAgain = null
;

2020-11-30 17:54 UTC, hazmat345 commented on src/ui/src/js/controllers/request_view.js
> +                $scope.msgPourItAgain = 'Unable to find command'
;

2020-11-30 17:54 UTC, hazmat345 commented on src/ui/src/js/controllers/request_view.js
> +        $scope.msgPourItAgain = 'Unable to find system'
;

2020-11-30 20:55 UTC, hazmat345 approved these changes
LGTM :+1:

2020-12-01 16:21 UTC, merged